### PR TITLE
Move CI to GitHub Actions

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Closes #94.

### CODE REVIEW

**Comment by starbelly** [comment]
Looks good to me! ❤️

**Comment by paulo-ferraz-oliveira** [comment]
@starbelly, something's off with the coverage badge. D'you know what it is?

**Comment by paulo-ferraz-oliveira** [comment]
Locally, at least, the file's generated where CI's expecting it.

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira 

Screen Shot 2021-03-04 at 10 44 40 AM

**Comment by paulo-ferraz-oliveira** [comment]
😄 what does that mean? We need more commits?

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira yeah, that's what it alludes to.

**Comment by paulo-ferraz-oliveira** [comment]
Probably needs at least 2 to make a comparison 😄

**Pull request merged**
