### PR TITLE
add support for CI friendly publishing

### PR DESCRIPTION
**Pull request by starbelly**
This allows a user to circumvent traditional config files and prompts suitable for automating CI workflows. 

Allows for the following: 

```
HEX_API_KEY=some_write_key rebar3 hex publish --yes
```

Look ma, no prompts!

### CODE REVIEW

**Comment by starbelly** [comment]
One last thing to add a `--yes` option.

**Comment by starbelly** [comment]
This one is good to go 🎅

**Comment by tsloughter** [comment]
I thought mix/hex were explicitly against a feature like this. But mix actually supports it?

**Comment by starbelly** [comment]
@tsloughter mix supports it https://hexdocs.pm/hex/Mix.Tasks.Hex.Config.html#content . See config overrides. 

  I thought about this myself a bit and came to the conclusion that people will inevitability automate this with or without this support. So, the question then becomes whether to discourage it in documentation or not, but that's another story.

**Comment by starbelly** [comment]
It should be noted mix also provides a `--yes` option on the publish task.

**Pull request merged**
