### PR TITLE
Allow to publish without prompt. Useful for scripts

### PR DESCRIPTION
**Pull request by tank-bohr**
I'am trying to set up automatic package publishing in CI on tag pushed event. Thus this thing is crucial to making it possible

### CODE REVIEW

**Comment by tsloughter** [comment]
You can get around it for now with http://blog.erlware.org/automatic-hex-package-publishing-with-travis-ci/

I'll think about this. My thinking was that these extra steps keep it from being done in regular use, viewing the output is important and can catch plenty of mistake -- I do all the time at least :).

**Comment by tank-bohr** [comment]
@tsloughter Thank you. I'll take your advice

**Comment by tank-bohr** [comment]
@tsloughter What will we do about it? I still believe it worth to merge. This option is false by default thus you still can catch the mistakes.
But if you don't think so then we should just close this PR

**Comment by tsloughter** [comment]
This actually isn't possible anymore because the key for publishing is encrypted on disk, requiring a password from the user to decrypt at the time of publishing. This is to prevent issues like when an npm package was stealing credentials.

**Pull request closed without merging**
